export const DATA_DEFAULT = [
  { name: 'NƯỚC SUỐI', price: 10000, type: 'DRINK' },
  { name: 'NƯỚC NGỌT', price: 15000, type: 'DRINK' },
  { name: 'NƯỚC TĂNG LỰC', price: 25000, type: 'DRINK' },
  { name: 'STRONGBOW', price: 30000, type: 'DRINK' },
  { name: 'TRÀ CHANH', price: 15000, type: 'DRINK' },
  { name: 'NƯỚC ÉP', price: 25000, type: 'DRINK' },
  { name: 'BIA', price: 22000, type: 'DRINK' },
  { name: 'BIA TO', price: 25000, type: 'DRINK' },

  // đồ ăn
  { name: 'BIM BIM MIX', price: 15000, type: 'FOOD' },
  { name: 'BIM BIM', price: 15000, type: 'FOOD' },
  { name: 'BIM BIM 10', price: 10000, type: 'FOOD' },
  { name: 'CHÂN GÀ', price: 15000, type: 'FOOD' },
  { name: 'KHÔ BÒ', price: 35000, type: 'FOOD' },
  { name: 'KHÔ GÀ', price: 35000, type: 'FOOD' },
  { name: 'MỰC BENTO', price: 10000, type: 'FOOD' },
  { name: 'ĐĨA XOÀI', price: 20000, type: 'FOOD' },
  { name: 'HOA QUẢ MIX 35', price: 35000, type: 'FOOD' },
  { name: 'HOA QUẢ MIX 55', price: 55000, type: 'FOOD' },
  { name: 'ĐẬU PHỘNG', price: 15000, type: 'FOOD' },
  { name: 'THUỐC LÁ', price: 20000, type: 'FOOD' },
  { name: 'ĐỒ SẤY', price: 15000, type: 'FOOD' },
  { name: 'TĂM CAY', price: 5000, type: 'FOOD' },
  { name: 'BÁNH TRÁNG', price: 10000, type: 'FOOD' },
  { name: 'HŨ KHÔ GÀ', price: 30000, type: 'FOOD' },
  { name: 'MÍT', price: 25000, type: 'FOOD' },
];
