export const DATA_DEFAULT = [
  {
    name: 'Box 1',
    defaultPricePerHour: 0,
    size: 'SMALL',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 2',
    defaultPricePerHour: 0,
    size: 'SMALL',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 3',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 4',
    defaultPricePerHour: 0,
    size: 'LARGE',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 5',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 6',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 7',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 8',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 9',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 10',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 11',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 12',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 13',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 14',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 15',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 16',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 17',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 18',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
  {
    name: 'Box 19',
    defaultPricePerHour: 0,
    size: 'MEDIUM',
    status: 'AVAILABLE',
  },
];
